# Generated by Django 3.0.4 on 2020-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=True, help_text='Designates whether this user is customer oor not!'),
        ),
    ]
