# Generated by Django 3.0.4 on 2020-04-26 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200426_1304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='Order_detail',
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.Order_detail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('completed', 'Completed')], default='new', max_length=10),
        ),
    ]
