# Generated by Django 3.0.4 on 2020-04-27 05:01

from django.conf import settings
from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_auto_20200426_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'is_customer': True}, on_delete=models.SET(orders.models.get_sentinel_user), related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='toppings',
            field=models.ManyToManyField(blank=True, default='None', null=True, to='orders.Topping'),
        ),
    ]
