# Generated by Django 3.0.4 on 2020-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200427_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='accepts_extra',
            field=models.BooleanField(default=False),
        ),
    ]
