# Generated by Django 3.0.4 on 2020-05-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200501_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('initiated', 'Initiated'), ('ready', 'Ready'), ('completed', 'Completed')], default='new', max_length=10),
        ),
    ]
